"""init

Revision ID: 092df09105f0
Revises: 
Create Date: 2020-10-02 02:43:32.118921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092df09105f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
