"""init

Revision ID: 382332488f0c
Revises: f8ab6f749372
Create Date: 2020-10-02 04:11:30.710078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382332488f0c'
down_revision = 'f8ab6f749372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qruser', '_id')
    op.drop_column('qrworker', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qrworker', sa.Column('_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('qruser', sa.Column('_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
