"""init

Revision ID: aa96fdbab850
Revises: f84205683e01
Create Date: 2020-09-30 16:04:06.770119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa96fdbab850'
down_revision = 'f84205683e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qrworker', sa.Column('linkdowload', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qrworker', 'linkdowload')
    # ### end Alembic commands ###
