"""init

Revision ID: f8ab6f749372
Revises: 092df09105f0
Create Date: 2020-10-02 03:05:42.876904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ab6f749372'
down_revision = '092df09105f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_school_year', sa.String(length=30), nullable=False),
    sa.Column('student_class', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
